### ISSUE TITLE
VD16 uniformity issue

### ISSUE THREAD

**Issue by linguistcrg** [CentreForDigitalHumanities/edpop-explorer#42]
While performing a search of the word "almanac", instead of getting this output:
`Performing query: almanac`

I get the following output:
`Performing query: VD16 and (1800)`

However, I still get results.

**Comment by tijmenbaarda** [comment]
This is expected, because some readers need to transform the query before forwarding them to the API. But I understand that this causes confusion! I'll add a note in the readme and then close the corresponding issues.
